homeassistant:

  # Name of the location where Home Assistant is running
  name: hamster

  # Authentication
  auth_providers:
    - type: homeassistant

  # Location required to calculate the time the sun rises and sets
  latitude: !secret LATITUDE
  longitude: !secret LONGITUDE

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ELEVATION

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin


# Debug logging
logger:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# MQTT support
mqtt:
  broker: !secret MQTT_HOST
  port: 1883
  client_id: homeassistant

mqtt_eventstream:
  publish_topic: homeassistant

# Enable REST API
api:

# Alexa support
alexa:

# IFTTT support
ifttt:
  key: !secret IFTTT_API_KEY

# PiHole statistics
# pi_hole:
#   - host: !secret PI_HOLE_HOST_1
#     name: hole
#     verify_ssl: false
#     api_key: !secret PI_HOLE_1_API_KEY_1

# Synology DSM
synology_dsm: !include devices/synology_dsm.yaml

# Track mobile devices
mobile_app:
discovery:

# homematicIP (cloud access)
homematicip_cloud: !include devices/homematicip_cloud.yaml

# MiLight
light: !include devices/light.yaml

# Broadlink Switches (433MHz sockets)
switch: !include devices/switch.yaml

# AVM Fritz!SmartHome
fritzbox: !include devices/fritzbox.yaml

# Tuya
tuya: !include devices/tuya.yaml

input_select: !include input_select.yaml

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
intent_script: !include intent_scripts.yaml
remote: !include remotes.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
