- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: template
  sensors:
    month:
      friendly_name: "Month"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%m') }}"
      icon_template: mdi:calendar-clock
    week_of_year:
      friendly_name: "Week of Year"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%W') }}"
      icon_template: mdi:calendar-clock

- platform: command_line
  name: RPi CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: RPi Power Status
  command: "./scripts/rpi_power_status.sh"

# - platform: xbox_live
#   api_key: !secret XAPI_API_KEY
#   xuid:
#     - !secret XAPI_USER_ID

#- platform: template
#  sensors:
#    climate_livingroom_temperature:
#      friendly_name: "Temperatur Wohnzimmer"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.wohnzimmer_wandthermostat', 'current_temperature') }}"
#- platform: template
#  sensors:
#    climate_kitchen_temperature:
#      friendly_name: "Temperatur Küche"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.kuche_wandthermostat', 'current_temperature') }}"
#- platform: template
#  sensors:
#    climate_workroom_temperature:
#      friendly_name: "Temperatur Hobbyraum"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.hobbyraum_wandthermostat', 'current_temperature') }}"
#- platform: template
#  sensors:
#    climate_bedroom_temperature:
#      friendly_name: "Temperatur Schlafzimmer"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.schlafzimmer_wandthermostat', 'current_temperature') }}"
#- platform: template
#  sensors:
#    climate_bathroom_temperature:
#      friendly_name: "Temperatur Bad"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.bad_wandthermostat', 'current_temperature') }}"

- platform: rest
  resource: https://extranet.marfis.tech/ocs/v2.php/apps/serverinfo/api/v1/info
  name: mft_extranet
  force_update: true