- platform: broadlink
  host: rfir-1.fritz.box
  mac: '34:EA:34:88:F5:44'
  type: rm2
  friendly_name: 'IR/RF Hub'
  switches:
    livingroom_desk_lamp:
      friendly_name: 'Wohnzimmer Schreibtischlampe'
      command_on: 'sgsyAAYTBhMGExIHBhMSBwYTBhIGExIHBhMSBwYTEgcGExIHBhMGExIHEgcGEwYTEgcSBwa5AAAAAAAA'
      command_off: 'sgcyAAYTBhMGExIHBhMTBwYSBhMGExIHBhMSBwYTEgcGExIHBhMHEhIHEgcSBxIHBhMGEwa5AAAAAAAA'
    livingroom_uplighter:
      friendly_name: 'Wohnzimmer Deckenfluter'
      command_on: 'sgAuAQYSBhIGEhEGBhISBgYSBRIGEhIGBhIRBwUTEQYGEhIGEQcRBgYSBhIGEgUTEQYSBga4BhIGEgYREgYGEhIGBhIFEgYSEgYFExEGBhISBgYSEQcRBhIGBhIGEgYSBRISBhIGBrgGEgUTBRISBgYSEgYFEgYSBhISBgYSEQYGEhIGBhIRBxEGEgYGEgYSBRMFEhIGEQcFuQUTBRIGEhIGBhIRBwUSBhIGEhEHBRMRBgYSEgYGEhEGEgYSBgYSBRIGEgYSEgYRBwW5BhEGEgYSEgYGEhEGBhIGEgYSEQcFEhIGBhIRBwUSEgYSBhEHBRMFEgYSBhISBhEGBrgGEgYSBhIRBwUSEgYGEgYSBRISBgYSEgYFExEGBhISBhEHEQcFEgYSBhIGEgUTBRIGAAXcAAAAAAAAAAAAAA=='
      command_off: 'sgCyAAYSEQcFEhIGEQcSBgUSBhISBhEHBRIGEga4BhIGEgUTEQYGEhIGBRIGEgYSEgYGEhEGBhISBgYSEQYSBhIGBhIFExEGEgYGEgYSBbkFEgYSBhISBgUSEgYGEgYSBRMRBgYSEgYGEhEGBhISBhIGEQYGEgYSEgYSBgUSBhIGuAYSBRMFEhIGBhIRBwUSBhIGEhEGBhISBgYSEgYGERIGBhIGEgUSBhIGEgYSBhEGEgYABdwAAAAAAAA='
    livingroom_globe:
      friendly_name: 'Wohnzimmer Globus'
      command_on: 'sgAOAQUSBhIGEgYSBRMFEhIGEgYGuAYSBRMFExEGBhISBgUTBRIGEhIGBRISBwUSEgYRBxEHBRMFEgUTBhIFEgYSEgYRBwW5BhIFEgYSEgYFExEHBRIGEgYSEQcFExEGBhISBhEHEQYGEgYSBhIFEwUSBhISBhEHBbkFEwUSBhISBgUTEQYGEgYSBhIRBgYSEgYGEhEHEQYSBgYSBhIFEwUSBhIGEhEHEQYGuAYSBhIGEhEGBhISBgYSBRMFExEGBhIRBwUTEQYSBhIGBRMFEgYSBhIGEgUTEQYSBga4BhIGEgUTEQYGEhIGBRMFEwUSEgYGEhEGBhISBhIGEQcFEgYSBhIFEwUSBhIGEgYSBQAF3AAAAAAAAAAAAAA='
      command_off: 'sgAMAQUSBhIGEhEHEQcFEgYSBrgGEgUTBRISBgYSEQcFEgYSBhIRBwUTEQYGEhIGEQcRBgYSBhIGEgUTEQYSBgYSBRMFuQUSBhIGEhEHBRISBgYSBhIFExEGBhISBgYSEQYSBhIGBhIFEwUSBhISBhEHBRIGEga4BhIFEwUTEQYGEhEHBRMFEgYSEgYGEhEHBRISBhIGEQcFEgYSBhIGEhEGEgYGEgYSBrgFEgYSBhISBgYSEQYGEgYSBhIRBwUSEgYGEhEHEQYSBgYSBhIFEgYSEgYSBgYSBRIGuAYSBhIFExEGBhISBgYSBRMFEhIGBhIRBwUSEgYGEhIGBRIGEgYSBhIGEQYSBhIGEgUABdwAAAAAAAAAAAAAAAA='
    bedroom_nightbulb:
      friendly_name: 'Schlafzimmer Nachtlicht'
      command_on: 'sgCuAAUSEgcFEgYSBRMFEgYSBhIRBxEHBbkFEgYSBRMRBwUTEQYGEgYSBRISBgYSEQcRBxEHBRISBgYSBRMFEgYSBRMFExEHEQYFuQYSBRMFEhIGBhIRBwUSBhIGEhEHBRMRBhIGEQcFExEGBhIGEgYSBRMFEgYSEQcRBwW5BRIGEgYSEQcFExEGBhIGEgUTEQYGEhIGEQcRBwUSEgYFEwUSBhIGEgUTBRMFEgYSBQAF3AAAAAAAAAAAAAA='
      command_off: 'sgACAQYSBRMFuQUTBRIGEhEHBRISBwUSBhIFExEGBhISBhEHEQcFEhIGBRMFEwUTBRISBhEHBRMFEga4BhIGEgUTEQcFEhIGBRMFEwUSEgYFExEHEQcRBgYSEgYFEwUTBRIGEhEHEQcFEgYSBbkGEgUTBRISBgYSEQcFEwUSBhIRBwUSEgcRBhIGBRMRBwUSBhIGEgUTEQYSBgUTBRMFuQUSBhIGEhEHBRMRBgYSBRMFExEGBhISBhEHEQYGEhIGBRMFEwUTBRISBhEHBRMFEga4BhIGEgUSEgYGEhEHBRMFEgYSEQcFExEGBhIRBwUTEQcFEgYSBhIFEwUSBhIGEgUTBQAF3AAAAAAAAA=='
    loggia_uplighter:
      friendly_name: 'Loggia Deckenfluter'
      command_on: 'sgcyAAYTBhMGExIHBhMSBwYTBhMGExIHEgcSBwYTEgcGExIHBhMGEwYTBhMGEwYTEgcSBwa5AAAAAAAA'
      command_off: 'shwyAAYTBhMGExIHBhMSCAYTBhMGExIHEgcSBwYTEgcGExIHBhMHEwcTBhMSBxIHBhMGEwa6AAAAAAAA'