- platform: broadlink
  host: 192.168.1.30
  mac: '34:EA:34:88:F5:44'
  switches:
    - name: 'livingroom_desklamp'
      command_on: 'sgsyAAYTBhMGExIHBhMSBwYTBhIGExIHBhMSBwYTEgcGExIHBhMGExIHEgcGEwYTEgcSBwa5AAAAAAAA'
      command_off: 'sgcyAAYTBhMGExIHBhMTBwYSBhMGExIHBhMSBwYTEgcGExIHBhMHEhIHEgcSBxIHBhMGEwa5AAAAAAAA'
    - name: 'livingroom_uplighter'
      command_on: 'sgAuAQYSBhIGEhEGBhISBgYSBRIGEhIGBhIRBwUTEQYGEhIGEQcRBgYSBhIGEgUTEQYSBga4BhIGEgYREgYGEhIGBhIFEgYSEgYFExEGBhISBgYSEQcRBhIGBhIGEgYSBRISBhIGBrgGEgUTBRISBgYSEgYFEgYSBhISBgYSEQYGEhIGBhIRBxEGEgYGEgYSBRMFEhIGEQcFuQUTBRIGEhIGBhIRBwUSBhIGEhEHBRMRBgYSEgYGEhEGEgYSBgYSBRIGEgYSEgYRBwW5BhEGEgYSEgYGEhEGBhIGEgYSEQcFEhIGBhIRBwUSEgYSBhEHBRMFEgYSBhISBhEGBrgGEgYSBhIRBwUSEgYGEgYSBRISBgYSEgYFExEGBhISBhEHEQcFEgYSBhIGEgUTBRIGAAXcAAAAAAAAAAAAAA=='
      command_off: 'sgCyAAYSEQcFEhIGEQcSBgUSBhISBhEHBRIGEga4BhIGEgUTEQYGEhIGBRIGEgYSEgYGEhEGBhISBgYSEQYSBhIGBhIFExEGEgYGEgYSBbkFEgYSBhISBgUSEgYGEgYSBRMRBgYSEgYGEhEGBhISBhIGEQYGEgYSEgYSBgUSBhIGuAYSBRMFEhIGBhIRBwUSBhIGEhEGBhISBgYSEgYGERIGBhIGEgUSBhIGEgYSBhEGEgYABdwAAAAAAAA='
    - name: 'livingroom_globe'
      command_on: 'sgAOAQUSBhIGEgYSBRMFEhIGEgYGuAYSBRMFExEGBhISBgUTBRIGEhIGBRISBwUSEgYRBxEHBRMFEgUTBhIFEgYSEgYRBwW5BhIFEgYSEgYFExEHBRIGEgYSEQcFExEGBhISBhEHEQYGEgYSBhIFEwUSBhISBhEHBbkFEwUSBhISBgUTEQYGEgYSBhIRBgYSEgYGEhEHEQYSBgYSBhIFEwUSBhIGEhEHEQYGuAYSBhIGEhEGBhISBgYSBRMFExEGBhIRBwUTEQYSBhIGBRMFEgYSBhIGEgUTEQYSBga4BhIGEgUTEQYGEhIGBRMFEwUSEgYGEhEGBhISBhIGEQcFEgYSBhIFEwUSBhIGEgYSBQAF3AAAAAAAAAAAAAA='
      command_off: 'sgAMAQUSBhIGEhEHEQcFEgYSBrgGEgUTBRISBgYSEQcFEgYSBhIRBwUTEQYGEhIGEQcRBgYSBhIGEgUTEQYSBgYSBRMFuQUSBhIGEhEHBRISBgYSBhIFExEGBhISBgYSEQYSBhIGBhIFEwUSBhISBhEHBRIGEga4BhIFEwUTEQYGEhEHBRMFEgYSEgYGEhEHBRISBhIGEQcFEgYSBhIGEhEGEgYGEgYSBrgFEgYSBhISBgYSEQYGEgYSBhIRBwUSEgYGEhEHEQYSBgYSBhIFEgYSEgYSBgYSBRIGuAYSBhIFExEGBhISBgYSBRMFEhIGBhIRBwUSEgYGEhIGBRIGEgYSBhIGEQYSBhIGEgUABdwAAAAAAAAAAAAAAAA='
    - name: 'bedroom_nightbulb'    
      command_on: 'sgCuAAUSEgcFEgYSBRMFEgYSBhIRBxEHBbkFEgYSBRMRBwUTEQYGEgYSBRISBgYSEQcRBxEHBRISBgYSBRMFEgYSBRMFExEHEQYFuQYSBRMFEhIGBhIRBwUSBhIGEhEHBRMRBhIGEQcFExEGBhIGEgYSBRMFEgYSEQcRBwW5BRIGEgYSEQcFExEGBhIGEgUTEQYGEhIGEQcRBwUSEgYFEwUSBhIGEgUTBRMFEgYSBQAF3AAAAAAAAAAAAAA='
      command_off: 'sgACAQYSBRMFuQUTBRIGEhEHBRISBwUSBhIFExEGBhISBhEHEQcFEhIGBRMFEwUTBRISBhEHBRMFEga4BhIGEgUTEQcFEhIGBRMFEwUSEgYFExEHEQcRBgYSEgYFEwUTBRIGEhEHEQcFEgYSBbkGEgUTBRISBgYSEQcFEwUSBhIRBwUSEgcRBhIGBRMRBwUSBhIGEgUTEQYSBgUTBRMFuQUSBhIGEhEHBRMRBgYSBRMFExEGBhISBhEHEQYGEhIGBRMFEwUTBRISBhEHBRMFEga4BhIGEgUSEgYGEhEHBRMFEgYSEQcFExEGBhIRBwUTEQcFEgYSBhIFEwUSBhIGEgUTBQAF3AAAAAAAAA=='
    - name: 'loggia_uplighter'      
      command_on: 'sgcyAAYTBhMGExIHBhMSBwYTBhMGExIHEgcSBwYTEgcGExIHBhMGEwYTBhMGEwYTEgcSBwa5AAAAAAAA'
      command_off: 'shwyAAYTBhMGExIHBhMSCAYTBhMGExIHEgcSBwYTEgcGExIHBhMHEwcTBhMSBxIHBhMGEwa6AAAAAAAA'

- platform: broadlink
  mac: 'C8:F7:42:16:97:09'
  host: 192.168.1.56

